"""Coverage and audit reporting for validate-pro generated cases."""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

from .adapters import ADAPTERS
from .dataset import DIFFICULTY_ORDER, Problem


@dataclass(frozen=True)
class GenerationEvent:
    """One generation or retention event used in audit reports."""

    frontend_id: str
    title: str
    difficulty: str
    kind: str
    status: str
    reason: str


def adapter_support_rows(problems: list[Problem]) -> list[dict[str, str]]:
    """Build support-matrix rows for all problem kinds in the selection."""

    by_kind: dict[str, list[Problem]] = defaultdict(list)
    for problem in problems:
        by_kind[problem.kind].append(problem)

    rows = []
    for kind in sorted(by_kind):
        kind_problems = by_kind[kind]
        supported = kind in ADAPTERS
        examples = ", ".join(f"{problem.frontend_id} {problem.title}" for problem in kind_problems[:5])
        rows.append(
            {
                "kind": kind,
                "supported": "yes" if supported else "no",
                "adapter": kind if supported else "",
                "problem_count": str(len(kind_problems)),
                "examples": examples,
            }
        )
    return rows


def retained_case_counts(cases_dir: Path) -> dict[str, int]:
    """Return retained case counts keyed by frontend id."""

    counts: dict[str, int] = {}
    if not cases_dir.exists():
        return counts
    for path in sorted(cases_dir.glob("*.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        counts[str(document.get("frontend_id", ""))] = len(document.get("cases", []))
    return counts


def write_adapter_support_report(path: Path, problems: list[Problem]) -> None:
    """Write the adapter support matrix as Markdown."""

    lines = [
        "# Validate Pro Adapter Support Matrix",
        "",
        "This report lists problem-shape kinds discovered in the selected dataset and whether validate-pro has a Python reference adapter for each kind.",
        "",
        "| Kind | Supported | Adapter | Problems | Examples |",
        "| --- | --- | --- | ---: | --- |",
    ]
    for row in adapter_support_rows(problems):
        lines.append(
            f"| `{row['kind']}` | {row['supported']} | `{row['adapter']}` | {row['problem_count']} | {row['examples']} |"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_adapter_support_report_cn(path: Path, problems: list[Problem]) -> None:
    """Write the adapter support matrix as Chinese Markdown."""

    lines = [
        "# Validate Pro Adapter 支持矩阵",
        "",
        "本报告列出所选 dataset 中出现的题型 kind，并说明 validate-pro 是否已经有对应的 Python 参考 adapter。",
        "",
        "| Kind | 是否支持 | Adapter | 题目数量 | 示例题目 |",
        "| --- | --- | --- | ---: | --- |",
    ]
    for row in adapter_support_rows(problems):
        supported = "是" if row["supported"] == "yes" else "否"
        lines.append(
            f"| `{row['kind']}` | {supported} | `{row['adapter']}` | {row['problem_count']} | {row['examples']} |"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_generation_audit_report(path: Path, problems: list[Problem], events: list[GenerationEvent], cases_dir: Path) -> None:
    """Write retained-case summary and failure reasons as Markdown."""

    counts = retained_case_counts(cases_dir)
    status_counts = Counter(event.status for event in events)
    reason_counts = Counter(event.reason for event in events if event.reason)
    difficulty_counts = Counter(problem.difficulty for problem in problems)
    supported_count = sum(1 for problem in problems if problem.kind in ADAPTERS)
    sorted_problems = sorted(problems, key=lambda problem: int(problem.frontend_id) if problem.frontend_id.isdigit() else 0)

    lines = [
        "# Validate Pro Generation Audit",
        "",
        "This report is generated by `Leetcode-QC/validate-pro/generate_cases.py`.",
        "",
        "## Summary",
        "",
        f"- Selected problems: {len(problems)}",
        f"- Adapter-supported problems: {supported_count}",
        f"- Problems with retained JSON cases: {len(counts)}",
        "",
        "## Difficulty Coverage",
        "",
        "| Difficulty | Problems |",
        "| --- | ---: |",
    ]
    for difficulty in DIFFICULTY_ORDER:
        lines.append(f"| {difficulty} | {difficulty_counts[difficulty]} |")

    lines.extend(["", "## Event Status", "", "| Status | Count |", "| --- | ---: |"])
    for status, count in sorted(status_counts.items()):
        lines.append(f"| `{status}` | {count} |")

    lines.extend(["", "## Failure Reasons", "", "| Reason | Count |", "| --- | ---: |"])
    for reason, count in sorted(reason_counts.items()):
        lines.append(f"| `{reason}` | {count} |")

    lines.extend(["", "## Retained Cases", "", "| Problem | Difficulty | Kind | Retained cases |", "| --- | --- | --- | ---: |"])
    for problem in sorted_problems:
        lines.append(f"| {problem.frontend_id} {problem.title} | {problem.difficulty} | `{problem.kind}` | {counts.get(problem.frontend_id, 0)} |")

    failures = [event for event in events if event.status != "retained"]
    lines.extend(["", "## Detailed Failures", "", "| Problem | Difficulty | Kind | Status | Reason |", "| --- | --- | --- | --- | --- |"])
    for event in failures:
        lines.append(f"| {event.frontend_id} {event.title} | {event.difficulty} | `{event.kind}` | `{event.status}` | `{event.reason}` |")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_generation_audit_report_cn(path: Path, problems: list[Problem], events: list[GenerationEvent], cases_dir: Path) -> None:
    """Write retained-case summary and failure reasons as Chinese Markdown."""

    counts = retained_case_counts(cases_dir)
    status_counts = Counter(event.status for event in events)
    reason_counts = Counter(event.reason for event in events if event.reason)
    difficulty_counts = Counter(problem.difficulty for problem in problems)
    supported_count = sum(1 for problem in problems if problem.kind in ADAPTERS)
    sorted_problems = sorted(problems, key=lambda problem: int(problem.frontend_id) if problem.frontend_id.isdigit() else 0)

    lines = [
        "# Validate Pro 生成审计报告",
        "",
        "本报告由 `Leetcode-QC/validate-pro/generate_cases.py` 生成。",
        "",
        "## 汇总",
        "",
        f"- 选中题目数：{len(problems)}",
        f"- 已有 adapter 支持的题目数：{supported_count}",
        f"- 已生成保留样例 JSON 的题目数：{len(counts)}",
        "",
        "## 难度覆盖",
        "",
        "| 难度 | 题目数量 |",
        "| --- | ---: |",
    ]
    for difficulty in DIFFICULTY_ORDER:
        lines.append(f"| {difficulty} | {difficulty_counts[difficulty]} |")

    lines.extend(["", "## 事件状态", "", "| 状态 | 数量 |", "| --- | ---: |"])
    for status, count in sorted(status_counts.items()):
        lines.append(f"| `{status}` | {count} |")

    lines.extend(["", "## 失败原因", "", "| 原因 | 数量 |", "| --- | ---: |"])
    for reason, count in sorted(reason_counts.items()):
        lines.append(f"| `{reason}` | {count} |")

    lines.extend(["", "## 保留样例", "", "| 题目 | 难度 | Kind | 保留样例数 |", "| --- | --- | --- | ---: |"])
    for problem in sorted_problems:
        lines.append(f"| {problem.frontend_id} {problem.title} | {problem.difficulty} | `{problem.kind}` | {counts.get(problem.frontend_id, 0)} |")

    failures = [event for event in events if event.status != "retained"]
    lines.extend(["", "## 失败明细", "", "| 题目 | 难度 | Kind | 状态 | 原因 |", "| --- | --- | --- | --- | --- |"])
    for event in failures:
        lines.append(f"| {event.frontend_id} {event.title} | {event.difficulty} | `{event.kind}` | `{event.status}` | `{event.reason}` |")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
