#!/usr/bin/env python
"""Generate README indexes for easy, medium, and hard solution directories."""

from __future__ import annotations

import argparse
from pathlib import Path

from leetcode_solutions.config import DIFFICULTY_ORDER, Paths
from leetcode_solutions.dataset_loader import filter_by_difficulty, load_questions
from leetcode_solutions.markdown_writer import problem_output_path


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description="Generate difficulty README indexes.")
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="Project root path.")
    return parser.parse_args()


def format_topics(problem: dict) -> str:
    """Return a comma-separated topic list for one problem."""

    topics = problem.get("topics") or []
    if not topics:
        return "-"
    return ", ".join(str(topic) for topic in topics)


def problem_row(problem: dict, root: Path) -> str:
    """Render one Markdown table row."""

    frontend_id = int(str(problem.get("frontend_id", "")).strip())
    title = str(problem.get("title", "")).strip()
    path = problem_output_path(problem, root)
    relative_link = path.relative_to(root / str(problem.get("difficulty", "")).lower())
    topics = format_topics(problem)
    return f"| {frontend_id:04d} | [{title}]({relative_link.as_posix()}) | {topics} |"


def render_readme(difficulty: str, problems: list[dict], root: Path, language: str) -> str:
    """Render one difficulty README."""

    lines: list[str] = []
    if language == "cn":
        lines.extend(
            [
                f"# {difficulty} 题目清单",
                "",
                f"本清单由 `scripts/generate_difficulty_readmes.py` 根据 `dataset/merged_problems.json` 生成。",
                "",
                f"题目数量：{len(problems)}",
                "",
                "| 编号 | 题目 | 分类 |",
                "| --- | --- | --- |",
            ]
        )
    else:
        lines.extend(
            [
                f"# {difficulty} Problem Index",
                "",
                "This index is generated by `scripts/generate_difficulty_readmes.py` from `dataset/merged_problems.json`.",
                "",
                f"Problem count: {len(problems)}",
                "",
                "| ID | Problem | Topics |",
                "| --- | --- | --- |",
            ]
        )

    lines.extend(problem_row(problem, root) for problem in problems)
    return "\n".join(lines).rstrip() + "\n"


def write_readmes(root: Path) -> None:
    """Write English and Chinese README files for all difficulty directories."""

    paths = Paths.from_root(root)
    questions = load_questions(paths.dataset)
    for difficulty in DIFFICULTY_ORDER:
        problems = filter_by_difficulty(questions, difficulty)
        output_dir = root / difficulty.lower()
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "README.md").write_text(render_readme(difficulty, problems, root, "en"), encoding="utf-8")
        (output_dir / "README.cn.md").write_text(render_readme(difficulty, problems, root, "cn"), encoding="utf-8")


def main() -> int:
    """Run the README generation."""

    args = parse_args()
    write_readmes(args.root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
