#!/usr/bin/env python
"""生成 Easy、Medium、Hard 目录下的题目清单 README。

这个脚本读取 `dataset/merged_problems.json`，按难度生成 6 个文件：

- `easy/README.md`
- `easy/README.cn.md`
- `medium/README.md`
- `medium/README.cn.md`
- `hard/README.md`
- `hard/README.cn.md`

每个清单包含题号、题名链接和 topics。链接路径复用
`leetcode_solutions.markdown_writer.problem_output_path()`，确保 README 中的
路径规则和实际生成题解文件的路径规则始终一致。
"""

from __future__ import annotations

import argparse
from pathlib import Path

from leetcode_solutions.config import DIFFICULTY_ORDER, Paths
from leetcode_solutions.dataset_loader import filter_by_difficulty, load_questions
from leetcode_solutions.markdown_writer import problem_output_path


def parse_args() -> argparse.Namespace:
    """解析命令行参数。

    返回：
        argparse.Namespace: 目前只包含 `root`，表示仓库根目录。
    """

    parser = argparse.ArgumentParser(description="Generate difficulty README indexes.")
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="Project root path.")
    return parser.parse_args()


def format_topics(problem: dict) -> str:
    """把单题 topics 格式化成逗号分隔文本。

    参数：
        problem: dataset 中的一道题。

    返回：
        str: 形如 `Array, Hash Table` 的分类文本；没有分类时返回 `-`。
    """

    topics = problem.get("topics") or []
    if not topics:
        return "-"
    return ", ".join(str(topic) for topic in topics)


def problem_row(problem: dict, root: Path) -> str:
    """渲染 README 表格中的一行题目信息。

    参数：
        problem: dataset 中的一道题。
        root: 仓库根目录，用于计算相对难度目录的链接路径。

    返回：
        str: Markdown 表格行，包含四位补零题号、题名链接和 topics。
    """

    frontend_id = int(str(problem.get("frontend_id", "")).strip())
    title = str(problem.get("title", "")).strip()
    path = problem_output_path(problem, root)
    relative_link = path.relative_to(root / str(problem.get("difficulty", "")).lower())
    topics = format_topics(problem)
    return f"| {frontend_id:04d} | [{title}]({relative_link.as_posix()}) | {topics} |"


def render_readme(difficulty: str, problems: list[dict], root: Path, language: str) -> str:
    """渲染某个难度的英文或中文 README 内容。

    参数：
        difficulty: 难度名，例如 `Easy`。
        problems: 该难度下按题号排序的题目列表。
        root: 仓库根目录。
        language: 输出语言，`en` 表示英文，`cn` 表示中文。

    返回：
        str: 完整 Markdown 文本，末尾包含一个换行。
    """

    lines: list[str] = []
    if language == "cn":
        lines.extend(
            [
                f"# {difficulty} 题目清单",
                "",
                f"本清单由 `scripts/generate_difficulty_readmes.py` 根据 `dataset/merged_problems.json` 生成。",
                "",
                f"题目数量：{len(problems)}",
                "",
                "| 编号 | 题目 | 分类 |",
                "| --- | --- | --- |",
            ]
        )
    else:
        lines.extend(
            [
                f"# {difficulty} Problem Index",
                "",
                "This index is generated by `scripts/generate_difficulty_readmes.py` from `dataset/merged_problems.json`.",
                "",
                f"Problem count: {len(problems)}",
                "",
                "| ID | Problem | Topics |",
                "| --- | --- | --- |",
            ]
        )

    lines.extend(problem_row(problem, root) for problem in problems)
    return "\n".join(lines).rstrip() + "\n"


def write_readmes(root: Path) -> None:
    """为三个难度目录写入英文和中文 README。

    参数：
        root: 仓库根目录。

    副作用：
        创建或覆盖 `easy/`、`medium/`、`hard/` 下的 `README.md` 和
        `README.cn.md`。
    """

    paths = Paths.from_root(root)
    questions = load_questions(paths.dataset)
    for difficulty in DIFFICULTY_ORDER:
        problems = filter_by_difficulty(questions, difficulty)
        output_dir = root / difficulty.lower()
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "README.md").write_text(render_readme(difficulty, problems, root, "en"), encoding="utf-8")
        (output_dir / "README.cn.md").write_text(render_readme(difficulty, problems, root, "cn"), encoding="utf-8")


def main() -> int:
    """执行 README 生成流程。

    返回：
        int: 生成成功返回 0。
    """

    args = parse_args()
    write_readmes(args.root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
